export type {
  Deal,
  AIRecommendationSlot,
  CheckoutSummary,
  SupportTicket,
  RefundPolicy,
  PriceBreakdown,
  MerchantInfo,
  BNPLOption,
  DealCategory,
  PaymentMethod,
  BNPLProvider,
  RefundWindowUnit,
  SupportIssueCategory,
} from "./deal";

export type { GrouponPreferences } from "./preferences";

export type {
  AnalyticsEvent,
  EventByName,
  LifestylePreference,
  BudgetRange,
  LocationRadiusMiles,
  SearchMode,
  AssistantResultAction,
  HelpSurface,
  // Phase 0
  QuizStartedEvent,
  LifestylePreferenceSelectedEvent,
  QuizCompletedEvent,
  QuizSkippedEvent,
  // Phase 1
  HomeScreenViewedEvent,
  FeedViewedEvent,
  DealCardImpressionEvent,
  DealCardTappedEvent,
  FeedScrolledEvent,
  // Phase 2
  SearchBarOpenedEvent,
  SearchSubmittedEvent,
  SearchFilterChangedEvent,
  SearchResultTappedEvent,
  AssistantQuerySubmittedEvent,
  AssistantResultActionTakenEvent,
  // Phase 3
  DealViewedEvent,
  HeroImageSwipedEvent,
  FinePrintExpandedEvent,
  PricingBreakdownExpandedEvent,
  RefundPolicyExpandedEvent,
  DealSavedEvent,
  BuyTappedEvent,
  BnplHintTappedEvent,
  // Phase 4
  CheckoutOpenedEvent,
  SlotSelectedEvent,
  PaymentMethodSelectedEvent,
  RecurringChargeAcknowledgedEvent,
  PurchaseConfirmedEvent,
  ThreeDsChallengeStartedEvent,
  ThreeDsChallengeSucceededEvent,
  ThreeDsChallengeFailedEvent,
  // Phase 5
  BookingConfirmationViewedEvent,
  AddToCalendarTappedEvent,
  // Phase 6
  MyGrouponsViewedEvent,
  VoucherViewedEvent,
  PostPurchaseHelpOpenedEvent,
  SupportChatOpenedEvent,
  SupportEscalatedToHumanEvent,
  SelfServeRefundStartedEvent,
  SelfServeRefundCompletedEvent,
} from "./analytics";
